; cnc-ddraw config for Diablo II Archipelago

[ddraw]
width=1496
height=1122
fullscreen=false
windowed=true
maintas=true
boxing=false
maxfps=-1
vsync=false
adjmouse=true
renderer=auto
shader=
savesettings=1
resizable=true
noactivateapp=false
hook=4
minfps=0
maxgameticks=0
limiter=false
nonexclusive=false
singlecpu=true
posX=462
posY=156
